server:
  port: 8252

spring:  datasource:    url: jdbc:h2:mem:currencydb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  h2:    console:      enabled: true
      
  application:    name: convertcurrency
  zipkin:
    base-url: http://192.168.99.100:9411/
        
  sleuth:
    sampler:
      probability: 1.0
    trace-id128: true  
eureka:  instance:    instance-id: ${spring.application.name}:${random.int} 
   
  client:    service-url:      defaultZone: http://localhost:8089/eureka
